name: OIDC Test
on:
  workflow_dispatch
permissions:
  id-token: write       # required for OIDC
  contents: read        # required to checkout code

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v5.0.0

      - name: configure aws credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: arn:aws:iam::555066115752:role/aws-oidc-test  # this is the role ARN we just created
          aws-region: ca-central-1  # you can use any region you want to work in

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: List S3 buckets
        run: aws s3 ls